#!/bin/bash

#
# Often in development mode, we retrieve a database from a production server
# and each users have their own password.
# Here we force all of them equal to usernames.

if [ "$RUNNING_ENV" = "dev" ] ; then

    if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
    then
        echo "Database does not exist, ignoring script"
        exit 0
    fi

    echo "Setting users' passwords to their usernames."

    psql << EOF

    UPDATE res_users SET password = login;

EOF

fi
